version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.4

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix coveralls.post --token "$COVERALLS_REPO_TOKEN"
